spring:
  application:
    name: amora_api

  config:
    import:
      - optional:file:.env[.properties]

  # Configurações do DataSource
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DATABASE_HOST}:${DATABASE_PORT}/${DATABASE_NAME}
    username: ${DATABASE_USER}  
    password: ${DATABASE_PASSWORD}

  # Configurações do Hibernate (opcional)
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      "[hibernate.format_sql]": true

  # Configurações do DevTools
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: false

springdoc:
  api-docs:
    path: /api-docs
  use-fqn: true

api:
  security:
    token:
      secret: ${JWT_SECRET:my-secret-key}